apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://devops.easyshopletsdeployit.shop/api"
  NEXTAUTH_URL: "https://devops.easyshopletsdeployit.shop/"
  NEXTAUTH_SECRET: "KzKw7/l718a1T7DWfHjcfTijND+xteVv37kdokb0Azw="
  JWT_SECRET: "+N5pq7OaJFc6lMbYznVCwOjQXzSvQVWb5GbI3AHtf+Y="
