apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  JWT_SECRET: "+N5pq7OaJFc6lMbYznVCwOjQXzSvQVWb5GbI3AHtf+Y="
  NEXTAUTH_SECRET: "KzKw7/l718a1T7DWfHjcfTijND+xteVv37kdokb0Azw="
